# Generated by Django 3.2.8 on 2021-11-30 19:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='groceryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='siteUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pantry_list', models.JSONField(null=True)),
                ('allergy_list', models.ManyToManyField(related_name='allergic_users', to='meal_planner_main.allergies')),
                ('grocery_list', models.ManyToManyField(related_name='users_who_own', to='meal_planner_main.groceryItems')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_ingredients', models.JSONField(null=True)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
                ('allergens_in_item', models.ManyToManyField(related_name='recipes_with_allergens', to='meal_planner_main.allergies')),
                ('author', models.ManyToManyField(related_name='recipe_list', to='meal_planner_main.siteUser')),
            ],
        ),
        migrations.CreateModel(
            name='forumPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('intro', models.CharField(max_length=200)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
                ('slug', models.CharField(max_length=200)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meal_planner_main.siteuser')),
            ],
        ),
    ]
