# Generated by Django 3.2.8 on 2021-12-03 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner_main', '0002_scheduledrecipe'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroceryList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=200)),
                ('ingredients', models.TextField()),
                ('calories', models.IntegerField()),
                ('item_id', models.CharField(max_length=200)),
            ],
        ),
    ]
