# Generated by Django 3.2.8 on 2021-12-03 19:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meal_planner_main', '0005_auto_20211203_1429'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['date_added']},
        ),
    ]
