# Generated by Django 3.2.8 on 2022-02-17 15:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='allergies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipe_name', models.CharField(max_length=200)),
                ('recipe_ingredients', models.JSONField(null=True)),
                ('date_added', models.DateTimeField(verbose_name='date published')),
                ('allergens_in_item', models.ManyToManyField(related_name='recipes_with_allergens', to='recipes.allergies')),
                ('author', models.ManyToManyField(related_name='recipe_list', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
