# Generated by Selenium IDE (edited)
import random
from selenium.webdriver.common.by import By
import undetected_chromedriver as uc


class TestCreateaccount():
    """Test that creates and logs into a new account."""

    def __init__(self):
        self.driver = uc.Chrome()

    def register_login(self):
        r1 = random.randint(10000000, 99999999) # random 8 digit number
        r2 = random.randint(10000000, 99999999)
        username = 'testaccount' + str(r1) # e.g. testaccount12345678
        email = username + '@email.com' # e.g. testaccount12345678@email.com
        password = 'pass' + str(r2) # e.g. pass23456789

        self.driver.get("http://localhost:8000/")
        self.driver.set_window_size(1024, 768)
        self.driver.find_element(By.LINK_TEXT, "Register").click()
        self.driver.find_element(By.ID, "id_username").send_keys(username)
        self.driver.find_element(By.ID, "id_email").send_keys(email)
        self.driver.find_element(By.ID, "id_password1").send_keys(password)
        self.driver.find_element(By.ID, "id_password2").click()
        self.driver.find_element(By.ID, "id_password2").send_keys(password)
        self.driver.find_element(By.CSS_SELECTOR, ".btn-primary").click()
        
    def logout(self):
        self.driver.find_element(By.LINK_TEXT, "Logout").click()

if __name__ == '__main__':
    test = TestCreateaccount()
    test.register_login()
    test.logout()
