branch-defaults:
  main:
    environment: django-env
environment-defaults:
  django-env:
    branch: null
    repository: null
global:
  application_name: django-tutorial
  default_ec2_keyname: my-keypair
  default_platform: Python 3.7 running on 64bit Amazon Linux 2
  default_region: us-west-2
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  sc: git
  workspace_type: Application
