# Generated by Django 3.2.8 on 2022-02-09 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='pantryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('expiration', models.DateField(default='')),
                ('userid', models.TextField(max_length=150)),
            ],
        ),
    ]
