# Generated by Django 3.2.8 on 2022-04-03 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_post_image'),
        ('forum', '0002_auto_20220403_1816'),
    ]

    operations = [
    ]
