# Generated by Django 3.2.8 on 2022-04-19 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='recipe_notes',
            field=models.TextField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
