# Generated by Django 3.2.8 on 2022-04-20 00:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_recipe_notes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='recipe_notes',
            field=models.TextField(default='', max_length=100),
        ),
    ]
