# Generated by Django 3.2.8 on 2022-04-03 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('grocery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='pantryItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveSmallIntegerField(default=0)),
                ('expiration', models.DateField(default=None, null=True)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='grocery.foodingredient')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
